### ISSUE TITLE
Implement v1.2 local hash calculation, pending JSON LD normalization library

### ISSUE THREAD

**Issue by kimdhamilton** [blockchain-certificates/BlockcertsFramework-iOS#14]
We need the ability to perform JSON LD normalization in order to perform the v1.2 local hash. This doesn't appear to be available for Flask yet.

**Comment by bedinotti** [comment]
This is mentioned in the #developers channel, but we've hit a problem the JSON-LD normalization. Our existing v1.2 certs aren't valid JSON-LD because of a design constraint where `@type` and `type` are treated as the same key.
https://github.com/json-ld/json-ld.org/issues/402

As such, the javascript implementation of the JSON-LD toolset complains that v1.2 certificates have colliding keywords. 
<img width="647" alt="screen shot 2016-09-22 at 4 24 20 pm" src="https://cloud.githubusercontent.com/assets/547866/18795197/9fe3d0b2-8180-11e6-9e41-01660b26994e.png">

**Comment by bedinotti** [comment]
Found the root issue. Our format currently adds an extra "@type" key to the `receipt` block. That's a Chainpoint v2 receipt, and their json-ld schema follows the emerging standard of aliasing "type" to "@type". Since we're trying to use that standard, the problem isn't with the JSON-LD parser or the schema, but instead with how we're creating the certificates. Indeed, v1.2 certificates we've created so far will (correctly) fail JSON-LD parsing.

On the plus side, the WKWebKit bridge I'm using to run [`jsonld.js`](https://github.com/digitalbazaar/jsonld.js) totally works as a stop-gap measure until we invest time in an iOS native JSON-LD library. It's been incorporated into the validation mechanism and tested with a v1.2 certificate that has been modified to pass JSON-LD parsing. Unfortunately, that's not a fully conclusive test, since it (correctly) fails validation comparing local to signed hashes. 

I'm going to leave this issue open until I can manually verify a published certificate.
